## Exercises  
## 练习

1. Prove that the transpose of the transpose of a matrix is the matrix itself: $(\mathbf{A}^\top)^\top = \mathbf{A}$.  
   证明矩阵转置的转置等于矩阵本身：$(\mathbf{A}^\top)^\top = \mathbf{A}$。

2. Given two matrices $\mathbf{A}$ and $\mathbf{B}$, show that sum and transposition commute: $\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top$.  
   给定两个矩阵 $\mathbf{A}$ 和 $\mathbf{B}$，证明矩阵求和与转置运算可以交换次序：$\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top$。

3. Given any square matrix $\mathbf{A}$, is $\mathbf{A} + \mathbf{A}^\top$ always symmetric? Can you prove the result by using only the results of the previous two exercises?  
   给定任意方阵 $\mathbf{A}$，$\mathbf{A} + \mathbf{A}^\top$ 是否总是对称矩阵？你能否仅使用前两道练习的结论来证明这一结果？

4. We defined the tensor `X` of shape (2, 3, 4) in this section. What is the output of `len(X)`? Write your answer without implementing any code, then check your answer using code.  
   本节定义了形状为 (2, 3, 4) 的张量 `X`。`len(X)` 的输出是什么？先在不编写任何代码的情况下写出答案，然后使用代码检查你的答案。

5. For a tensor `X` of arbitrary shape, does `len(X)` always correspond to the length of a certain axis of `X`? What is that axis?  
   对于具有任意形状的张量 `X`，`len(X)` 是否总是对应于 `X` 某个轴的长度？它对应的是哪个轴？

6. Run `A / A.sum(axis=1)` and see what happens. Can you analyze the results?  
   运行 `A / A.sum(axis=1)` 并观察会发生什么。你能分析其结果吗？

7. When traveling between two points in downtown Manhattan, what is the distance that you need to cover in terms of the coordinates, i.e., in terms of avenues and streets? Can you travel diagonally?  
   在曼哈顿市中心的两个地点之间移动时，按照坐标来计算，也就是按照大道和街道来计算，你需要走多远？你能沿对角线方向行进吗？

8. Consider a tensor of shape (2, 3, 4). What are the shapes of the summation outputs along axes 0, 1, and 2?  
   考虑一个形状为 (2, 3, 4) 的张量。分别沿轴 0、轴 1 和轴 2 求和后，输出的形状是什么？

9. Feed a tensor with three or more axes to the `linalg.norm` function and observe its output. What does this function compute for tensors of arbitrary shape?  
   将一个具有三个或更多轴的张量传入 `linalg.norm` 函数，并观察其输出。对于任意形状的张量，这个函数计算的是什么？

10. Consider three large matrices, say $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{14}}$, initialized with Gaussian random variables. You want to compute the product $\mathbf{A} \mathbf{B} \mathbf{C}$. Is there any difference in memory footprint and speed, depending on whether you compute $(\mathbf{A} \mathbf{B}) \mathbf{C}$ or $\mathbf{A} (\mathbf{B} \mathbf{C})$. Why?  
    考虑三个大型矩阵，比如 $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$、$\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ 和 $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{14}}$，它们均使用高斯随机变量进行初始化。你想计算乘积 $\mathbf{A} \mathbf{B} \mathbf{C}$。采用 $(\mathbf{A} \mathbf{B}) \mathbf{C}$ 或 $\mathbf{A} (\mathbf{B} \mathbf{C})$ 的计算顺序，在内存占用和速度方面是否存在差异？为什么？

11. Consider three large matrices, say $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{16}}$. Is there any difference in speed depending on whether you compute $\mathbf{A} \mathbf{B}$ or $\mathbf{A} \mathbf{C}^\top$? Why? What changes if you initialize $\mathbf{C} = \mathbf{B}^\top$ without cloning memory? Why?  
    考虑三个大型矩阵，比如 $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$、$\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ 和 $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{16}}$。计算 $\mathbf{A} \mathbf{B}$ 与计算 $\mathbf{A} \mathbf{C}^\top$ 的速度是否存在差异？为什么？如果在不克隆内存的情况下初始化 $\mathbf{C} = \mathbf{B}^\top$，情况会发生什么变化？为什么？

12. Consider three matrices, say $\mathbf{A}, \mathbf{B}, \mathbf{C} \in \mathbb{R}^{100 \times 200}$. Construct a tensor with three axes by stacking $[\mathbf{A}, \mathbf{B}, \mathbf{C}]$. What is the dimensionality? Slice out the second coordinate of the third axis to recover $\mathbf{B}$. Check that your answer is correct.  
    考虑三个矩阵，比如 $\mathbf{A}, \mathbf{B}, \mathbf{C} \in \mathbb{R}^{100 \times 200}$。通过堆叠 $[\mathbf{A}, \mathbf{B}, \mathbf{C}]$ 构造一个具有三个轴的张量。该张量的维度是多少？对第三个轴的第二个坐标进行切片，以恢复 $\mathbf{B}$。检查你的答案是否正确。

In [9]:
import torch
A = torch.arange(24).reshape(2,3,4)
len(A)

2

In [27]:
# A / A.sum(axis=1)
A.sum(axis=0).shape

torch.Size([3, 4])

In [41]:
B = torch.arange(3,5, dtype=torch.float32).reshape(2)
torch.linalg.norm(B)

tensor(5.)

In [67]:
LA = torch.randn(2**10, 2**16)
LB = torch.randn(2**16, 2**5)
LC = torch.randn(2**5, 2**16)
LC = LB.T

In [53]:
(LA@LB) @ LC

tensor([[-1775.5791,   -30.1273,  -981.7304,  ...,   728.9293,   439.4891,
          2359.9114],
        [ 1636.1414,   654.3763,   949.8992,  ...,   257.3162,  -254.2145,
           293.4496],
        [ 2274.6145,  2855.8198,  1695.1758,  ...,  1103.5554,  -389.9003,
         -1228.5605],
        ...,
        [-2134.2976, -2430.7087,   359.1640,  ...,   -36.8369, -3482.7136,
          -766.1598],
        [  193.6474,     6.1105,  1199.4620,  ...,   648.6364,  -942.5501,
           912.0560],
        [ -598.2925,    -3.5175,  -423.7727,  ..., -1585.9104,  1636.5594,
           390.3171]])

In [54]:
LA@ (LB @ LC)

tensor([[-1775.5785,   -30.1277,  -981.7299,  ...,   728.9284,   439.4898,
          2359.9119],
        [ 1636.1425,   654.3756,   949.8990,  ...,   257.3162,  -254.2143,
           293.4495],
        [ 2274.6143,  2855.8196,  1695.1769,  ...,  1103.5543,  -389.8994,
         -1228.5604],
        ...,
        [-2134.2986, -2430.7080,   359.1646,  ...,   -36.8364, -3482.7107,
          -766.1601],
        [  193.6478,     6.1112,  1199.4618,  ...,   648.6360,  -942.5513,
           912.0554],
        [ -598.2916,    -3.5174,  -423.7723,  ..., -1585.9122,  1636.5591,
           390.3174]])

In [50]:
import timeit
import tracemalloc
import gc

# 预热，避免首次运行的初始化开销影响结果
_ = (LA @ LB) @ LC

# --------------------
# 测量执行时间
# --------------------
repeat = 5
number = 10

times = timeit.repeat(
    stmt="(LA @ LB) @ LC",
    globals={"LA": LA, "LB": LB, "LC": LC},
    repeat=repeat,
    number=number
)

best_avg_time = min(times) / number
mean_avg_time = sum(times) / (repeat * number)

print(f"最佳单次耗时：{best_avg_time:.6f} 秒")
print(f"平均单次耗时：{mean_avg_time:.6f} 秒")

# --------------------
# 测量内存
# --------------------
gc.collect()
tracemalloc.start()

before_current, _ = tracemalloc.get_traced_memory()

result = (LA @ LB) @ LC

after_current, peak = tracemalloc.get_traced_memory()
tracemalloc.stop()

net_memory = after_current - before_current
peak_memory = peak - before_current

print(f"内存净增加：{net_memory / 1024**2:.3f} MiB")
print(f"执行期间峰值增加：{peak_memory / 1024**2:.3f} MiB")


最佳单次耗时：0.023857 秒
平均单次耗时：0.024248 秒
内存净增加：0.000 MiB
执行期间峰值增加：0.010 MiB


In [55]:
import timeit
import tracemalloc
import gc

# 预热，减少首次运行初始化开销的影响
_ = LA @ (LB @ LC)

# --------------------
# 测量执行时间
# --------------------
repeat = 5
number = 10

times = timeit.repeat(
    stmt="LA @ (LB @ LC)",
    globals={"LA": LA, "LB": LB, "LC": LC},
    repeat=repeat,
    number=number
)

best_avg_time = min(times) / number
mean_avg_time = sum(times) / (repeat * number)

print(f"最佳单次耗时：{best_avg_time:.6f} 秒")
print(f"平均单次耗时：{mean_avg_time:.6f} 秒")

# --------------------
# 测量 Python 层内存
# --------------------
gc.collect()
tracemalloc.start()

before_current, _ = tracemalloc.get_traced_memory()

result = LA @ (LB @ LC)

after_current, peak = tracemalloc.get_traced_memory()
tracemalloc.stop()

net_memory = after_current - before_current
peak_memory = peak - before_current

print(f"内存净增加：{net_memory / 1024**2:.3f} MiB")
print(f"执行期间峰值增加：{peak_memory / 1024**2:.3f} MiB")


最佳单次耗时：5.128381 秒
平均单次耗时：5.148676 秒
内存净增加：0.001 MiB
执行期间峰值增加：0.011 MiB


In [ ]:
LA@LB

tensor([[ 1.5223e+01,  2.0899e+02,  3.8950e+02,  ..., -4.3863e+02,
         -1.2534e+02, -1.1930e+02],
        [ 2.4752e+02,  1.1708e+02, -8.6036e+01,  ..., -5.0790e+01,
         -2.6089e+01,  2.3573e+02],
        [ 1.6603e+02, -3.6458e+02,  9.1209e+01,  ...,  9.1395e+02,
          4.1730e+01,  6.5730e+02],
        ...,
        [-2.0754e+02,  6.4463e+01,  3.2073e+02,  ...,  9.8850e+01,
          9.7383e+01, -6.0907e-01],
        [ 2.1497e+01,  3.1079e+02,  1.2536e+01,  ...,  1.4657e+02,
         -1.8499e+01,  1.1976e+02],
        [-3.0013e+02, -4.6514e+01,  2.4154e+02,  ...,  7.9341e+01,
         -5.9553e+02, -1.0097e+02]])

In [69]:
# 预热，减少首次运行初始化开销的影响
_ = LA@LB

# --------------------
# 测量执行时间
# --------------------
repeat = 5
number = 10

times = timeit.repeat(
    stmt="LA@LB",
    globals={"LA": LA, "LB": LB, "LC": LC},
    repeat=repeat,
    number=number
)

best_avg_time = min(times) / number
mean_avg_time = sum(times) / (repeat * number)

print(f"最佳单次耗时：{best_avg_time:.6f} 秒")
print(f"平均单次耗时：{mean_avg_time:.6f} 秒")
print(LB.shape)

最佳单次耗时：0.011068 秒
平均单次耗时：0.011267 秒
torch.Size([65536, 32])


In [57]:
LA@(LC.T)

tensor([[ 3.5249e-01,  1.5220e+02, -1.5290e+02,  ...,  2.3509e+02,
          4.2495e+01, -1.1032e+02],
        [-4.0397e+01,  1.3937e+02, -1.1472e+02,  ..., -5.0014e+01,
          1.8987e+02,  5.3467e+02],
        [ 1.1178e+02, -3.6553e+02,  1.6099e+01,  ...,  2.4356e+02,
          1.4004e+01, -5.0628e+02],
        ...,
        [ 4.5712e+02,  6.0182e+01,  3.7836e+02,  ..., -1.2519e+02,
         -2.0725e+02,  1.4543e+02],
        [-5.2132e+01, -3.2803e+01, -1.0761e+02,  ...,  3.3680e+01,
         -1.1083e+02, -3.3062e+01],
        [ 6.2420e+02,  2.6921e+02, -5.1409e+02,  ...,  2.6446e+02,
          9.8757e+00, -2.6525e+02]])

In [68]:
# 预热，减少首次运行初始化开销的影响
_ = LA@(LC.T)

# --------------------
# 测量执行时间
# --------------------
repeat = 5
number = 10

times = timeit.repeat(
    stmt="LA@(LC.T)",
    globals={"LA": LA, "LB": LB, "LC": LC},
    repeat=repeat,
    number=number
)

best_avg_time = min(times) / number
mean_avg_time = sum(times) / (repeat * number)

print(f"最佳单次耗时：{best_avg_time:.6f} 秒")
print(f"平均单次耗时：{mean_avg_time:.6f} 秒")
print(LC.T.shape)

最佳单次耗时：0.010996 秒
平均单次耗时：0.011153 秒
torch.Size([65536, 32])


In [101]:
A1 = torch.randn(100, 200)
B1 = torch.randn(100, 200)
C1 = torch.randn(100, 200)


In [102]:
X1 = torch.torch.stack([A1, B1, C1], dim=0)
OB1 = X1[1, :, :]
OB1

tensor([[-0.0941, -0.8962,  0.5962,  ..., -1.1781,  0.3232,  0.4326],
        [-0.1990, -0.7210,  1.0313,  ..., -0.7651, -0.6990, -0.2807],
        [-0.1214, -1.1110, -1.0217,  ..., -0.6993, -0.5976, -1.5555],
        ...,
        [-0.0935,  0.7014,  1.7460,  ...,  0.3352, -1.1854, -1.5001],
        [ 0.4979,  0.3046,  0.2840,  ...,  0.6935,  1.1456,  0.7677],
        [-0.5904, -0.2422,  0.9092,  ...,  0.2439, -0.0438,  0.2963]])

In [103]:
X1 = torch.torch.stack([A1, B1, C1], dim=1)
print(X1.shape)
OB2 = X1[:, 1, :]
OB2

torch.Size([100, 3, 200])


tensor([[-0.0941, -0.8962,  0.5962,  ..., -1.1781,  0.3232,  0.4326],
        [-0.1990, -0.7210,  1.0313,  ..., -0.7651, -0.6990, -0.2807],
        [-0.1214, -1.1110, -1.0217,  ..., -0.6993, -0.5976, -1.5555],
        ...,
        [-0.0935,  0.7014,  1.7460,  ...,  0.3352, -1.1854, -1.5001],
        [ 0.4979,  0.3046,  0.2840,  ...,  0.6935,  1.1456,  0.7677],
        [-0.5904, -0.2422,  0.9092,  ...,  0.2439, -0.0438,  0.2963]])

In [104]:
X1 = torch.torch.stack([A1, B1, C1], dim=2)
print(X1.shape)
OB3 = X1[:, :, 1]
OB3

torch.Size([100, 200, 3])


tensor([[-0.0941, -0.8962,  0.5962,  ..., -1.1781,  0.3232,  0.4326],
        [-0.1990, -0.7210,  1.0313,  ..., -0.7651, -0.6990, -0.2807],
        [-0.1214, -1.1110, -1.0217,  ..., -0.6993, -0.5976, -1.5555],
        ...,
        [-0.0935,  0.7014,  1.7460,  ...,  0.3352, -1.1854, -1.5001],
        [ 0.4979,  0.3046,  0.2840,  ...,  0.6935,  1.1456,  0.7677],
        [-0.5904, -0.2422,  0.9092,  ...,  0.2439, -0.0438,  0.2963]])

In [105]:
B1 == OB1,B1 == OB2, B1==OB3

(tensor([[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]]),
 tensor([[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]]),
 tensor([[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]])